# Generated by Django 5.1 on 2024-09-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
